export enum Roles {
  ROLE_HOST_OWNER = 'ROLE_HOST_OWNER',
  ROLE_HOST_ADMIN = 'ROLE_HOST_ADMIN',
  ROLE_TENANT = 'ROLE_TENANT',
  ROLE_PLATFORM_OWNER = 'ROLE_PLATFORM_OWNER',
  ROLE_PLATFORM_ADMIN = 'ROLE_PLATFORM_ADMIN',
  ROLE_PLATFORM_USER = 'ROLE_PLATFORM_USER',
}
